### ISSUE TITLE
API: list all msgfee

### ISSUE THREAD

**Issue by orkunkl** [iov-one/bns#11]
We need a REST API endpoint that lists all the `msgfees` like we have for escrows, eg http://exchangenet-bnsapi.iov.one/escrow/escrows.

The endpoint should be: http://exchangenet-bnsapi.iov.one/msgfee/msgfees

- [ ] The endpoint format of /singular/plural and that it doesn't have a trailing slash.

**Comment by orkunkl** [comment]
Apparently `msgfee` bucket is not registered to queries. Need to investigate further.

**Comment by orkunkl** [comment]
I will contact old devs to inspect further if the implementation is intentional.

**Comment by orkunkl** [comment]
Depends on this PR: https://github.com/iov-one/weave/pull/1168

**Comment by davepuchyr** [comment]
https://github.com/iov-one/weave/pull/1168 exposes `gconf/msgfee`.  We need to see the message fees like `msgfee` in the genesis file:
```
[
  {
    "fee": "10 IOV",
    "msg_path": "username/register_token"
  },
  {
    "fee": "1 IOV",
    "msg_path": "username/change_token_targets"
  },
  {
    "fee": "10 IOV",
    "msg_path": "username/transfer_token"
  }
]

```
