### ISSUE TITLE
Create endpoint for balances 

### ISSUE THREAD

**Issue by orkunkl** [iov-one/bns#14]
We need to include an endpoint for balances.  We want an endpoint that responds with data like from `BNSCLI_TM_ADDR=http://167.172.104.185:31140 bnscli query -path '/wallets' -data C1721181E83376EF978AA4A9A38A5E27C08C7BB2`  eg.
  ```
{
    "Key": "636173683ac1721181e83376ef978aa4a9a38a5e27c08c7bb2",
    "Value": {
      "metadata": {
        "schema": 1
      },
      "coins": [
        {
          "whole": 9773,
          "fractional": 550000000,
          "ticker": "IOV"
        }
      ]
    }
  }
```
The endpoint should be `/cash/balances` and list all balances when no parameter is given and should list a single balance if given an owner parameter in either hex or bech32 format.

**Comment by orkunkl** [comment]
It is better to have 2 API's. One for single wallet query and the other is for prefix/offset query. It will be easier to implement thus will be a better API design.

**Comment by davepuchyr** [comment]
A single endpoint for all balances as well as individual balances will be consistent with the other endpoints.  Can you not follow the work that Piotr did for `//account/domains/`, for example?

**Comment by orkunkl** [comment]
@davepuchyr That will not be easy to implement because: the current implementation of key queries(`cash/balance/{addr}`) works by stripping the last part and using in the query. For making huge queries we need the offset query parameter `cash/balance?offset=`. After all there will not be much change api wise.
