### ISSUE TITLE
Refactor DOMAIN env to be HOST and PORT

### ISSUE THREAD

**Issue by orkunkl** [iov-one/bns#15]
the env var DOMAN should be HOST and we need to add PORT, so that the available endpoints don't 404 localhost. The list of endpoints should be like `//HOST:PORT/info/`, etc.

- [ ]  Note the double // is not prefixed with http(s) .

**Comment by davepuchyr** [comment]
We could just rename `DOMAIN` to `HOST_PORT` or similar and have the onus on the user to make sure that it's well-formed with the colon if a colon required.
