### ISSUE TITLE
Bnsapi compatibility with weave v0.21.2

### ISSUE THREAD

**Issue by annatorok** [iov-one/bns#16]
We need to investigate if the `bnsapi` app can be made compatible with weave `v0.21.2`, the mainnet version.  If it is compatible then we need an endpoint for `usernames`, just like we already have for `accounts`.

**Comment by orkunkl** [comment]
The most effective breaking change after `v0.21.2` is the implementation of native indexes which is used by range queries. 

In bnsapi we use range queries to run paginated queries on bns. This means we can use the endpoints that return multiple values using offset such as `multisig/contracts?offset=`. 

But this is achievable. Just a function that uses `prefixes` to query the bns needs to be implemented. Then we can proceed to implementing `username` queries. But this will take 2 days I assume. @annatorok @davepuchyr should I proceed or is there something higher priority?

**Comment by antoineherzog** [comment]
Right now, we just want to add the /username/[orkun*iov] endpoint, this endpoint should be working with v0.21.2 because it is a simple abci_query with a data with a key. Could you do that today? then We can deploy the BNSAPI for IOV Name Service Mainnet, this task is super important.

**Comment by antoineherzog** [comment]
@orkunkl

**Comment by orkunkl** [comment]
Ofc it'll be done by the end of the day and deployed

**Comment by antoineherzog** [comment]
Wonderfull!

**Comment by antoineherzog** [comment]
@orkunkl any update

**Comment by orkunkl** [comment]
https://github.com/iov-one/bns/tree/weave-v0.21.2-release is where the release for old mainnet in.
